# Generated by Django 3.0.7 on 2020-07-03 23:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recording', '0002_auto_20200702_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voice',
            old_name='voice_name',
            new_name='initiator',
        ),
        migrations.RemoveField(
            model_name='voice',
            name='voice_record',
        ),
        migrations.AddField(
            model_name='voice',
            name='collective',
            field=models.FileField(default='none', upload_to='C:\\Users\\Aubrey\\Desktop\\semester3\\code\\project-NChant\\nchant\\media/audio'),
        ),
        migrations.AddField(
            model_name='voice',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voice',
            name='description',
            field=models.CharField(default='none', max_length=300),
        ),
        migrations.AddField(
            model_name='voice',
            name='image',
            field=models.ImageField(default='C:\\Users\\Aubrey\\Desktop\\semester3\\code\\project-NChant\\nchant\\media/imgdefault.jpg', upload_to='C:\\Users\\Aubrey\\Desktop\\semester3\\code\\project-NChant\\nchant\\media/img'),
        ),
        migrations.AddField(
            model_name='voice',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 3, 23, 24, 20, 311607, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='voice',
            name='seed',
            field=models.FileField(default='none', upload_to='C:\\Users\\Aubrey\\Desktop\\semester3\\code\\project-NChant\\nchant\\media/audio'),
        ),
        migrations.AddField(
            model_name='voice',
            name='title',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
