# Generated by Django 3.0.7 on 2020-07-08 17:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recording', '0004_auto_20200704_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='voice',
            name='onset',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='voice',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 8, 17, 58, 20, 345919, tzinfo=utc), verbose_name='date published'),
        ),
    ]
