# Generated by Django 3.0.7 on 2020-07-23 21:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recording', '0005_auto_20200708_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voice',
            name='collective',
            field=models.FileField(default='none', upload_to='C:\\Users\\Aubrey\\Desktop\\semester3\\code\\git_proj\\nchant_wechat\\media'),
        ),
        migrations.AlterField(
            model_name='voice',
            name='image',
            field=models.ImageField(default='C:\\Users\\Aubrey\\Desktop\\semester3\\code\\git_proj\\nchant_wechat\\mediadefault.jpg', upload_to='C:\\Users\\Aubrey\\Desktop\\semester3\\code\\git_proj\\nchant_wechat\\media'),
        ),
        migrations.AlterField(
            model_name='voice',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 23, 21, 37, 33, 161491, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='voice',
            name='seed',
            field=models.FileField(default='none', upload_to='C:\\Users\\Aubrey\\Desktop\\semester3\\code\\git_proj\\nchant_wechat\\media'),
        ),
    ]
